### ISSUE TITLE
Can't deploy to Tomcat

### ISSUE THREAD

**Issue by j-hudecek** [thehyve/dntp-portal#265]
I'm on Ubuntu 16.04. I can run DNTP just fine with mvn spring-boot:run, but when I deploy it to tomcat 7 I get this exception (and similar more) on startup:

       [ERROR] o.s.b.SpringApplication - Application startup failed
    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedServletContainerCustomizerBeanPostProcessor': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataSourceAdvisor': Cannot resolve reference to bean 'methodSecurityMetadataSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'methodSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration.setPermissionEvaluator(java.util.List); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customPermissionEvaluator': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: business.security.CustomPermissionService business.security.CustomPermissionEvaluator.permissionService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customPermissionService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private business.services.RequestService business.security.CustomPermissionService.requestService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private business.services.LabRequestService business.services.RequestService.labRequestService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'labRequestService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private business.services.RequestFormService business.services.LabRequestService.requestFormService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestFormService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private business.services.RequestPropertiesService business.services.RequestFormService.requestPropertiesService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestPropertiesService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: business.services.FileService business.services.RequestPropertiesService.fileService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fileService': Invocation of init method failed; nested exception is java.nio.file.AccessDeniedException: upload
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:478)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:240)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:687)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:150)
        at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:130)
        at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5573)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1091)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1980)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

From googling it seems to be a rights issue but which folder is the problem?

**Comment by gijskant** [comment]
The application expects there to be a writable directory `upload` in the current working directory. I'm not sure what location that should be for Tomcat.
We do not use an existing Tomcat instance for deployments, but use the built-in tomcat container of Spring Boot instead. We use a daemon like `upstart` or `systemd` to run the `war`-file generated with `mvn package`.
The script we run is like this:
```bash
java -jar -server -Xms2g -Xmx2g -XX:MaxPermSize=512m -Djava.awt.headless=true -Dserver.port=${internal_port} -Dspring.profiles.active=prod -Dspring.datasource.url=${database_url} -Djava.security.egd=file:/dev/./urandom -Ddntp.server-name=${hostname} -Ddntp.server-port=443 -Ddntp.reply-address=${email} -Dspring.config.location=${properties_file} ${war_file}
```
Please let us know if you still encounter problems.

**Comment by j-hudecek** [comment]
Thanks!
